name: Cache Node and NPM Dependencies

runs:
  using: composite
  steps:
    - name: Testing composite action
      shell: bash
      env:
       EVENT: ${{ toJson(github.event) }}
       GITHUB: ${{ toJson(github) }}
      run: |
        echo "github.event_name" ${{github.event_name}}
        echo "github.event.type" ${{github.event.type}}
        echo "github.event_path" ${{github.event_path}}
        echo $EVENT
        echo $GITHUB
        echo "github.event.pull_request.title" ${{github.event.pull_request.title}}
        echo "github.workspace" ${{github.workspace}}
        echo "github.sha" ${{github.sha}}
        echo "github.ref" ${{github.ref}}
        echo "github.run_id" ${{github.run_id}}

      
