name: Cache Node and NPM Dependencies

runs:
  using: composite
  steps:
    - name: Testing composite action
      shell: bash
      env:
       EVENT: ${{ toJson(github.event) }}
       GITHUB: ${{ toJson(github) }}
       ENV: ${{ toJson(env) }}
      run: |
        echo $TEST
        echo $ENV
        echo ${{env.TEST}}

      
