name: "02 - Workflow Events"
on: 
  schedule:
      - cron: "37 10 * * *"
  push:
  pull_request:
  workflow_dispatch: 
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: "Show the trigger"
        run: echo "This workflow was triggered by a '${{ github.event_name }}' event"
