name: "04 - Using Actions"
run-name: 06 - Contexts | DEBUG - ${{ inputs.debug }}

on: 
    push:
    workflow_dispatch:
      inputs:
        debug:
            description: Enable debug mode
            default: false
            required: false
            type: boolean

env:
  MY_WORKFLOW_VAR: workflow
  MY_OVERWRITTEN_VAR: workflow

jobs:
    echo-data:
        runs-on: ubuntu-latest
        env:
            MY_JOB_VAR: job
            MY_OVERWRITTEN_VAR: override-job
        steps:
            - name: Display Info
              run: |
                echo "Event name: ${{ github.event_name }}"
                echo "Ref: ${{ github.ref }}"
                echo "SHA: ${{ github.sha }}"
                echo "Repository: ${{ github.repository }}"
                echo "Repository Owner: ${{ github.repository_owner }}"
                echo "Actor: ${{ github.actor }}"
                echo "Workflow: ${{ github.workflow }}"
                echo "Action: ${{ github.action }}"
                echo "Run ID: ${{ github.run_id }}"
                echo "Run Number: ${{ github.run_number }}"
            - name: Retrieve Variable
              run: echo "The value of the variable is ${{ vars.MY_VAR}}"
            - name: Print Environment Variables
              env:
                MY_OVERWRITTEN_VAR: override-step
              run: |
                echo "Workflow: $MY_WORKFLOW_VAR"
                echo "Job: $MY_JOB_VAR"
                echo "Overwritten: $MY_OVERWRITTEN_VAR"
            - name: Print Environment Variables again
              run: |
                echo "Workflow: $MY_WORKFLOW_VAR"
                echo "Job: $MY_JOB_VAR"
                echo "Overwritten: $MY_OVERWRITTEN_VAR"

