name: 15 - Working with Matrices

on:
  workflow_dispatch:

jobs:
  single-matrix:
    name: ubuntu-${{ matrix.number }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        number: [1, 2, 3]
    steps:
      - name: Show number
        run: |
          echo "Matrix number is ${{ matrix.number }}" |
          echo "Job name is ${{ job }}" |
          echo "Job number is ${{ job.check_run_id }}"
