name: 99 - Test Composite Event

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: TESt COMPOSITE
        uses: ./.github/actions/composite-cache-deps
